#![cfg(unix)]

//! End-to-end coverage for bounded console Test options using installed Cargo.

use rustrace::{
    replay_tui::ReplayController,
    session::{ConsoleStart, ProductionSession, create_bundle},
    verify::{AssignmentReferenceStatus, SubmittedSourceStatus, VerificationStatus, verify_path},
};
use rustrace_model::{
    CaptureCompleteness, CommandCaptureMode, CommandOutcome, ConsoleStdinRoute, ConsoleStdoutRoute,
    ControlledAction, ControlledCommandFinished, ControlledCommandStarted, DecodeOutcome,
    DecodePolicy, Event, MAX_COMMAND_CHUNK_BYTES, OutputStream, decode_envelope,
};
use rustrace_workspace::assignment_package::{ExtractionLimits, extract_assignment_package};
use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    sync::atomic::{AtomicU64, Ordering},
    time::{Duration, Instant},
};

const MANIFEST: &[u8] = br#"format_version = 1
course_id = "course"
assignment_id = "real-test-options"
assignment_version = "v1"
title = "Real Cargo test options"
toolchain = "1.98.1"
edition = "2024"
allowed_paths = ["Cargo.toml", "Cargo.lock", "src/*.rs"]
[commands]
check = ["cargo", "check"]
test = ["cargo", "test"]
run = ["cargo", "run"]
clippy = ["cargo", "clippy"]
format = ["cargo", "fmt"]
"#;

const CARGO_TOML: &[u8] = br#"[package]
name = "rustrace-test-options-fixture"
version = "0.1.0"
edition = "2024"

[workspace]
"#;

const CARGO_LOCK: &[u8] = br#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "rustrace-test-options-fixture"
version = "0.1.0"
"#;

const SOURCE: &[u8] = br#"#[cfg(test)]
mod tests {
    #[test]
    fn alpha_visible() {
        println!("ALPHA_STDOUT_MARKER");
        dbg!("ALPHA_STDERR_MARKER");
    }

    #[test]
    fn beta_visible() {
        println!("BETA_STDOUT_MARKER");
        eprintln!("BETA_STDERR_MARKER");
    }

    #[test]
    fn fails_when_requested() {
        if std::path::Path::new("target/force-failure").exists() {
            assert_eq!(1, 2, "FAILED_ASSERTION_MARKER");
        }
    }
}
"#;

const SUCCESS_MARKERS: &[&str] = &[
    "ALPHA_STDOUT_MARKER",
    "ALPHA_STDERR_MARKER",
    "BETA_STDOUT_MARKER",
    "BETA_STDERR_MARKER",
];

struct Fixture {
    base: PathBuf,
    workspace: PathBuf,
    assignment: PathBuf,
    assignment_bytes: Vec<u8>,
    extracted: rustrace_workspace::assignment_package::ExtractedAssignment,
}

impl Fixture {
    fn new() -> Self {
        static NEXT: AtomicU64 = AtomicU64::new(0);
        let base = std::env::temp_dir().join(format!(
            "rustrace-real-test-options-{}-{}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir(&base).unwrap();
        let base = fs::canonicalize(base).unwrap();
        let assignment = base.join("assignment.rta");
        let assignment_bytes = assignment_package();
        fs::write(&assignment, &assignment_bytes).unwrap();
        let workspace = base.join("assignment.work");
        let extracted = extract_assignment_package(
            fs::File::open(&assignment).unwrap(),
            &workspace,
            ExtractionLimits::default(),
        )
        .unwrap();
        Self {
            base,
            workspace,
            assignment,
            assignment_bytes,
            extracted,
        }
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.base);
    }
}

struct RunCase {
    command: &'static str,
    tail: &'static [&'static str],
    present: &'static [&'static str],
    absent: &'static [&'static str],
}

struct ObservedRun {
    tail: Vec<String>,
    live: Vec<u8>,
    outcome: CommandOutcome,
    absent: &'static [&'static str],
}

struct RecordedRun {
    start: ControlledCommandStarted,
    stdout: Vec<u8>,
    stderr: Vec<u8>,
    finish: Option<ControlledCommandFinished>,
}

#[test]
fn real_cargo_console_test_options_verify_and_replay() {
    let fixture = Fixture::new();
    let mut session =
        ProductionSession::start_from_assignment(&fixture.workspace, &fixture.extracted).unwrap();
    let tools = session.discover_toolchain().unwrap().clone();
    assert!(
        !tools.has_blockers(),
        "installed pinned toolchain is required"
    );
    let expected_prefix = expected_argv_prefix(&tools);

    let cases = [
        RunCase {
            command: "cargo test alpha_visible",
            tail: &["alpha_visible"],
            present: &["tests::alpha_visible", "1 passed"],
            absent: &[
                "tests::beta_visible",
                "tests::fails_when_requested",
                "ALPHA_STDOUT_MARKER",
                "ALPHA_STDERR_MARKER",
                "BETA_STDOUT_MARKER",
                "BETA_STDERR_MARKER",
            ],
        },
        RunCase {
            command: "cargo test",
            tail: &[],
            present: &[
                "tests::alpha_visible",
                "tests::beta_visible",
                "tests::fails_when_requested",
                "3 passed",
            ],
            absent: SUCCESS_MARKERS,
        },
        RunCase {
            command: "cargo test definitely_no_matching_test",
            tail: &["definitely_no_matching_test"],
            present: &["running 0 tests", "0 passed"],
            absent: &[
                "tests::alpha_visible",
                "tests::beta_visible",
                "tests::fails_when_requested",
                "ALPHA_STDOUT_MARKER",
                "ALPHA_STDERR_MARKER",
                "BETA_STDOUT_MARKER",
                "BETA_STDERR_MARKER",
            ],
        },
        RunCase {
            command: "cargo test alpha_visible -- --nocapture",
            tail: &["alpha_visible", "--", "--nocapture"],
            present: &["ALPHA_STDOUT_MARKER", "ALPHA_STDERR_MARKER", "1 passed"],
            absent: &["BETA_STDOUT_MARKER", "BETA_STDERR_MARKER"],
        },
        RunCase {
            command: "cargo test beta_visible -- --no-capture",
            tail: &["beta_visible", "--", "--no-capture"],
            present: &["BETA_STDOUT_MARKER", "BETA_STDERR_MARKER", "1 passed"],
            absent: &["ALPHA_STDOUT_MARKER", "ALPHA_STDERR_MARKER"],
        },
        RunCase {
            command: "cargo test -- --show-output",
            tail: &["--", "--show-output"],
            present: &[
                "ALPHA_STDOUT_MARKER",
                "ALPHA_STDERR_MARKER",
                "BETA_STDOUT_MARKER",
                "BETA_STDERR_MARKER",
                "3 passed",
            ],
            absent: &[],
        },
    ];

    let mut observed = Vec::new();
    for case in cases {
        let (live, outcome) = run_console(&mut session, case.command, 0);
        assert_text_contains(&live, case.present, case.command);
        assert_text_omits(&live, case.absent, case.command);
        assert_unchanged(&fixture.workspace);
        observed.push(ObservedRun {
            tail: case.tail.iter().map(|value| (*value).to_owned()).collect(),
            live,
            outcome,
            absent: case.absent,
        });
    }

    fs::write(fixture.workspace.join("target/force-failure"), b"fail").unwrap();
    let (live, outcome) = run_console(&mut session, "cargo test fails_when_requested", 101);
    assert_text_contains(
        &live,
        &[
            "tests::fails_when_requested",
            "FAILED_ASSERTION_MARKER",
            "FAILED",
        ],
        "cargo test fails_when_requested",
    );
    observed.push(ObservedRun {
        tail: vec!["fails_when_requested".to_owned()],
        live,
        outcome,
        absent: &[],
    });
    fs::remove_file(fixture.workspace.join("target/force-failure")).unwrap();
    assert_unchanged(&fixture.workspace);
    assert_eq!(
        fs::read(&fixture.assignment).unwrap(),
        fixture.assignment_bytes
    );

    let receipt = session.finalize("student-1").unwrap();
    let final_workspace = receipt
        .final_workspace()
        .iter()
        .map(|(path, bytes)| (path.as_str().to_owned(), bytes.clone()))
        .collect::<BTreeMap<_, _>>();
    assert_eq!(final_workspace, expected_workspace());
    let bundle = create_bundle(&receipt, &fixture.base.join("submission.zip"))
        .unwrap()
        .path;

    let report = verify_path(&bundle, Some(&fixture.assignment));
    assert!(report.is_clean(), "{report:#?}");
    assert_eq!(report.package_structure, VerificationStatus::Ok);
    assert_eq!(report.event_chain, VerificationStatus::Ok);
    assert_eq!(report.checkpoint_hashes, VerificationStatus::Ok);
    assert_eq!(report.replay, VerificationStatus::Ok);
    assert_eq!(report.submitted_source_match, SubmittedSourceStatus::Ok);
    assert_eq!(report.assignment_reference, AssignmentReferenceStatus::Ok);

    let mut replay = ReplayController::open(&bundle).unwrap();
    assert!(replay.timeline_available());
    assert!(replay.verification_report().is_clean());
    let recorded = recorded_runs(&mut replay);
    assert_eq!(recorded.len(), observed.len());

    for (index, (actual, expected)) in recorded.iter().zip(&observed).enumerate() {
        let mut argv = expected_prefix.clone();
        argv.extend(["test".to_owned(), "--locked".to_owned()]);
        argv.extend(expected.tail.iter().cloned());
        assert_eq!(actual.start.argv, argv, "run {index}");
        assert_eq!(actual.start.action, ControlledAction::Test, "run {index}");
        let route = actual.start.console.as_ref().expect("console route");
        assert_eq!(route.stdin, ConsoleStdinRoute::Closed, "run {index}");
        assert_eq!(route.stdout, ConsoleStdoutRoute::Console, "run {index}");

        let finish = actual.finish.as_ref().expect("recorded finish");
        assert_eq!(finish.outcome, expected.outcome, "run {index}");
        assert_eq!(
            finish.stdout.mode,
            CommandCaptureMode::Captured,
            "run {index}"
        );
        assert_eq!(
            finish.stderr.mode,
            CommandCaptureMode::Captured,
            "run {index}"
        );
        assert_eq!(
            finish.stdout.completeness,
            CaptureCompleteness::Complete,
            "run {index}"
        );
        assert_eq!(
            finish.stderr.completeness,
            CaptureCompleteness::Complete,
            "run {index}"
        );
        assert_eq!(
            finish.stdout.bytes,
            actual.stdout.len() as u64,
            "run {index}"
        );
        assert_eq!(
            finish.stderr.bytes,
            actual.stderr.len() as u64,
            "run {index}"
        );
        assert!(
            finish.stdout.bytes + finish.stderr.bytes <= actual.start.output_limit,
            "run {index} exceeded its recorded output bound"
        );

        let mut recorded_output = actual.stdout.clone();
        recorded_output.extend_from_slice(&actual.stderr);
        assert_text_omits(
            &recorded_output,
            expected.absent,
            &format!("replayed run {index}"),
        );
        for marker in markers_in(&expected.live) {
            assert!(
                recorded_output
                    .windows(marker.len())
                    .any(|bytes| bytes == marker),
                "run {index} live marker {:?} missing from recorded bytes",
                String::from_utf8_lossy(marker)
            );
        }
    }

    let last = replay.positions().last().expect("terminal replay event");
    replay.select(last).unwrap();
    let replay_source = replay
        .selected_event()
        .unwrap()
        .source
        .iter()
        .cloned()
        .collect::<BTreeMap<_, _>>();
    assert_eq!(replay_source, expected_workspace());
    assert_eq!(
        fs::read(&fixture.assignment).unwrap(),
        fixture.assignment_bytes
    );
}

fn run_console(
    session: &mut ProductionSession,
    command: &str,
    exit_code: i32,
) -> (Vec<u8>, CommandOutcome) {
    assert_eq!(
        session.start_console_command(command).unwrap(),
        ConsoleStart::Started,
        "{command}"
    );
    assert!(!session.console_accepts_stdin(), "{command}");
    let until = Instant::now() + Duration::from_secs(60);
    while session.command_active() && Instant::now() < until {
        session
            .poll_command()
            .unwrap_or_else(|error| panic!("{command}: {error}"));
        std::thread::sleep(Duration::from_millis(2));
    }
    assert!(!session.command_active(), "{command} exceeded hang guard");
    let outcome = session.command_outcome().cloned().expect("command outcome");
    assert_eq!(
        outcome,
        CommandOutcome::Exited { code: exit_code },
        "{command}"
    );
    let live = session.console_output();
    assert!(
        !live.is_empty(),
        "{command} produced no live console output"
    );
    (live, outcome)
}

fn expected_argv_prefix(report: &rustrace::toolchain::ToolchainReport) -> Vec<String> {
    let rustup = report
        .probes
        .iter()
        .find(|probe| probe.component == "rustup" && probe.purpose == "version")
        .and_then(|probe| probe.argv.first())
        .expect("observed rustup launcher")
        .clone();
    let cargo = report
        .probes
        .iter()
        .find(|probe| probe.component == "cargo" && probe.purpose == "resolve")
        .expect("resolved Cargo")
        .stdout
        .trim()
        .to_owned();
    vec![
        rustup,
        "run".to_owned(),
        report
            .selected_toolchain
            .clone()
            .expect("selected pinned toolchain"),
        cargo,
    ]
}

fn recorded_runs(replay: &mut ReplayController) -> Vec<RecordedRun> {
    let positions = replay.positions().collect::<Vec<_>>();
    let mut runs = Vec::<RecordedRun>::new();
    for position in positions {
        replay.select(position).unwrap();
        let selected = replay.selected_event().unwrap();
        let DecodeOutcome::Decoded(envelope) =
            decode_envelope(&selected.event_bytes, DecodePolicy::RejectUnsupported).unwrap()
        else {
            panic!("validated replay exposed an unsupported event")
        };
        match envelope.event {
            Event::ControlledCommandStarted(start) => runs.push(RecordedRun {
                start,
                stdout: Vec::new(),
                stderr: Vec::new(),
                finish: None,
            }),
            Event::ControlledCommandOutput(output) => {
                let run = runs
                    .iter_mut()
                    .find(|run| run.start.command_id == output.command_id)
                    .expect("output without recorded start");
                let target = match output.stream {
                    OutputStream::Stdout => &mut run.stdout,
                    OutputStream::Stderr => &mut run.stderr,
                };
                assert_eq!(output.offset, target.len() as u64);
                let bytes = output.original_bytes().unwrap();
                assert!(bytes.len() <= MAX_COMMAND_CHUNK_BYTES);
                target.extend(bytes);
            }
            Event::ControlledCommandFinished(finish) => {
                let run = runs
                    .iter_mut()
                    .find(|run| run.start.command_id == finish.command_id)
                    .expect("finish without recorded start");
                assert!(run.finish.replace(finish).is_none());
            }
            _ => {}
        }
    }
    runs
}

fn assert_text_contains(output: &[u8], values: &[&str], command: &str) {
    let output = String::from_utf8_lossy(output);
    for value in values {
        assert!(
            output.contains(value),
            "{command}: missing {value:?} in {output:?}"
        );
    }
}

fn assert_text_omits(output: &[u8], values: &[&str], command: &str) {
    let output = String::from_utf8_lossy(output);
    for value in values {
        assert!(
            !output.contains(value),
            "{command}: exposed {value:?} in {output:?}"
        );
    }
}

fn markers_in(output: &[u8]) -> impl Iterator<Item = &'static [u8]> + '_ {
    const MARKERS: [&[u8]; 5] = [
        b"ALPHA_STDOUT_MARKER",
        b"ALPHA_STDERR_MARKER",
        b"BETA_STDOUT_MARKER",
        b"BETA_STDERR_MARKER",
        b"FAILED_ASSERTION_MARKER",
    ];
    MARKERS
        .into_iter()
        .filter(|marker| output.windows(marker.len()).any(|bytes| bytes == *marker))
}

fn assert_unchanged(workspace: &Path) {
    assert_eq!(fs::read(workspace.join("src/lib.rs")).unwrap(), SOURCE);
    assert_eq!(fs::read(workspace.join("Cargo.lock")).unwrap(), CARGO_LOCK);
}

fn expected_workspace() -> BTreeMap<String, Vec<u8>> {
    BTreeMap::from([
        ("Cargo.lock".to_owned(), CARGO_LOCK.to_vec()),
        ("Cargo.toml".to_owned(), CARGO_TOML.to_vec()),
        ("src/lib.rs".to_owned(), SOURCE.to_vec()),
    ])
}

fn assignment_package() -> Vec<u8> {
    let mut archive = Vec::new();
    for (path, contents) in [
        ("assignment.toml", MANIFEST),
        ("starter/Cargo.toml", CARGO_TOML),
        ("starter/Cargo.lock", CARGO_LOCK),
        ("starter/src/lib.rs", SOURCE),
    ] {
        let mut header = [0_u8; 512];
        header[..path.len()].copy_from_slice(path.as_bytes());
        write_octal(&mut header[100..108], 0o644);
        write_octal(&mut header[108..116], 0);
        write_octal(&mut header[116..124], 0);
        write_octal(&mut header[124..136], contents.len() as u64);
        write_octal(&mut header[136..148], 0);
        header[148..156].fill(b' ');
        header[156] = b'0';
        header[257..263].copy_from_slice(b"ustar\0");
        header[263..265].copy_from_slice(b"00");
        let checksum: u64 = header.iter().map(|byte| u64::from(*byte)).sum();
        header[148..156].copy_from_slice(format!("{checksum:06o}\0 ").as_bytes());
        archive.extend_from_slice(&header);
        archive.extend_from_slice(contents);
        archive.resize(archive.len().next_multiple_of(512), 0);
    }
    archive.resize(archive.len() + 1024, 0);
    archive
}

fn write_octal(field: &mut [u8], value: u64) {
    let encoded = format!("{:0width$o}\0", value, width = field.len() - 1);
    field.copy_from_slice(encoded.as_bytes());
}
