#!/usr/bin/env python3
"""Drive real cargo add followed by cargo check through the 80x24 console."""
import errno
import fcntl
import io
import json
import os
import pathlib
import pty
import re
import select
import struct
import subprocess
import sys
import tarfile
import tempfile
import termios
import time

from test_home import isolate
isolate()

binary = str(pathlib.Path(sys.argv[1]).resolve())
root = pathlib.Path(tempfile.mkdtemp(prefix="rustrace-dependency-pty-")).resolve()
work = root / "assignment.work"
manifest = b'''format_version = 1
course_id = "course"
assignment_id = "dependency-pty"
assignment_version = "v1"
title = "Dependency PTY"
toolchain = "1.98.1"
edition = "2024"
allowed_paths = ["Cargo.toml", "Cargo.lock", "src/*.rs"]
[commands]
check = ["cargo", "check"]
test = ["cargo", "test"]
run = ["cargo", "run"]
clippy = ["cargo", "clippy"]
format = ["cargo", "fmt"]
'''
cargo_toml = b'''[package]
name = "dependency_pty"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
'''
cargo_lock = b'''# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "dependency_pty"
version = "0.1.0"
'''
package = root / "assignment.rta"
with tarfile.open(package, "w", format=tarfile.USTAR_FORMAT) as archive:
    for name, content in [
        ("assignment.toml", manifest),
        ("starter/Cargo.toml", cargo_toml),
        ("starter/Cargo.lock", cargo_lock),
        ("starter/src/main.rs", b"fn main() {}\n"),
    ]:
        info = tarfile.TarInfo(name)
        info.size = len(content)
        info.mode = 0o600
        archive.addfile(info, io.BytesIO(content))
data = package.read_bytes()
while data.endswith(bytes(512)):
    data = data[:-512]
package.write_bytes(data + bytes(1024))

master, slave = pty.openpty()
fcntl.ioctl(slave, termios.TIOCSWINSZ, struct.pack("HHHH", 24, 80, 0, 0))


def own_terminal():
    os.setsid()
    fcntl.ioctl(0, termios.TIOCSCTTY, 0)


proc = subprocess.Popen(
    [binary, "work", str(package)],
    stdin=slave,
    stdout=slave,
    stderr=slave,
    preexec_fn=own_terminal,
    cwd=root,
    env={**os.environ, "TERM": "xterm-256color", "RUSTUP_AUTO_INSTALL": "0"},
)
os.close(slave)
transcript = bytearray()


def rendered_screen():
    """Reconstruct the 80x24 cursor-addressed Ratatui screen."""
    screen = [[" "] * 80 for _ in range(24)]
    row = column = 0
    text = transcript.decode("utf-8", "replace")
    for part in re.split(r"(\x1b\[[0-?]*[ -/]*[@-~])", text):
        if part.startswith("\x1b["):
            if part[2:3] == "?":
                if part == "\x1b[?1049h":
                    screen = [[" "] * 80 for _ in range(24)]
                    row = column = 0
                continue
            code = part[-1]
            values = [int(value or "0") for value in part[2:-1].split(";")]
            amount = values[0] or 1
            if code in ("H", "f"):
                row = amount - 1
                column = (values[1] or 1) - 1 if len(values) > 1 else 0
            elif code == "G":
                column = amount - 1
            elif code == "A":
                row = max(0, row - amount)
            elif code == "B":
                row += amount
            elif code == "C":
                column += amount
            elif code == "D":
                column = max(0, column - amount)
            elif code == "J" and values[0] == 2:
                screen = [[" "] * 80 for _ in range(24)]
            elif code == "K" and 0 <= row < 24:
                start = 0 if values[0] in (1, 2) else column
                end = column + 1 if values[0] == 1 else 80
                screen[row][start:end] = [" "] * (end - start)
            continue
        for character in part:
            if character == "\r":
                column = 0
            elif character == "\n":
                row += 1
            elif character >= " ":
                if 0 <= row < 24 and 0 <= column < 80:
                    screen[row][column] = character
                column += 1
    return "\n".join("".join(line) for line in screen)


def read_once(timeout=.05):
    if not select.select([master], [], [], timeout)[0]:
        return False
    try:
        chunk = os.read(master, 65536)
    except OSError as error:
        if error.errno == errno.EIO:
            return False
        raise
    transcript.extend(chunk)
    assert len(transcript) < 4 * 1024 * 1024, "PTY transcript exceeded bound"
    return bool(chunk)


def wait_for(predicate, description, seconds=90):
    deadline = time.monotonic() + seconds
    while time.monotonic() < deadline:
        read_once()
        if predicate():
            return
        if proc.poll() is not None:
            break
    raise AssertionError(
        f"timed out waiting for {description}; tail={bytes(transcript[-4000:])!r}"
    )


def wait_for_exit(description, seconds=60):
    deadline = time.monotonic() + seconds
    while time.monotonic() < deadline:
        read_once()
        returncode = proc.poll()
        if returncode is not None:
            return returncode
    raise AssertionError(
        f"timed out waiting for {description}; tail={bytes(transcript[-4000:])!r}"
    )


def captures():
    return list((work / ".rustrace").glob("command-*-capture.json"))


def inactive():
    marker = work / ".rustrace/command-activity.json"
    return marker.exists() and not json.loads(marker.read_bytes())["active"]


try:
    wait_for(lambda: b"files" in transcript and work.exists(), "workspace UI", 30)
    os.write(master, b"\x1b[20~")  # F9
    wait_for(
        lambda: " CONSOLE " in rendered_screen() and "> ▏" in rendered_screen(),
        "focused console prompt",
        15,
    )
    os.write(master, b"cargo add itoa\r")
    wait_for(
        lambda: len(captures()) >= 1
        and inactive()
        and b"itoa" in (work / "Cargo.toml").read_bytes(),
        "real cargo add completion",
    )
    lock_after_add = (work / "Cargo.lock").read_bytes()
    os.write(master, b"cargo check\r")
    wait_for(lambda: len(captures()) >= 2 and inactive(), "locked cargo check completion")
    assert (work / "Cargo.lock").read_bytes() == lock_after_add
    os.write(master, b"\x11")  # Ctrl-Q
    returncode = wait_for_exit("clean editor exit")
    while read_once(.01):
        pass
    assert returncode == 0, bytes(transcript[-8000:])
    assert b"\x1b[?2004l" in transcript and b"\x1b[?1049l" in transcript
    print(f"ROOT={root}")
except Exception:
    proc.kill()
    proc.wait()
    print(f"ROOT={root}")
    raise
finally:
    os.close(master)
