"""Assert ANSI token colours survive invalid Rust in the real 80x24 work TUI."""

import fcntl
import io
import os
import pty
import select
import signal
import struct
import subprocess
import sys
import tarfile
import tempfile
import termios
import time

from test_home import isolate
isolate()


BINARY = sys.argv[1]
WIDTH = 80
HEIGHT = 24
MANIFEST = b'''format_version = 1
course_id = "demo"
assignment_id = "highlighting"
assignment_version = "v1"
title = "Highlighting"
toolchain = "1.98.1"
edition = "2024"
allowed_paths = ["Cargo.toml", "Cargo.lock", "src/*.rs"]
[commands]
check = ["cargo", "check"]
test = ["cargo", "test"]
run = ["cargo", "run"]
clippy = ["cargo", "clippy"]
format = ["cargo", "fmt"]
'''
SOURCE = b'fn main() {\n    let message = "kept";\n}'


def package_at(root):
    package = os.path.join(root, "assignment.rta")
    archive_bytes = io.BytesIO()
    with tarfile.open(fileobj=archive_bytes, mode="w", format=tarfile.USTAR_FORMAT) as archive:
        for name, contents in [
            ("assignment.toml", MANIFEST),
            ("starter/Cargo.toml", b'[package]\nname = "highlighting"\nversion = "0.1.0"\nedition = "2024"\n\n[workspace]\n'),
            ("starter/Cargo.lock", b'# This file is automatically @generated by Cargo.\nversion = 4\n'),
            ("starter/src/main.rs", SOURCE),
        ]:
            info = tarfile.TarInfo(name)
            info.size = len(contents)
            info.mode = 0o600
            archive.addfile(info, io.BytesIO(contents))
    data = archive_bytes.getvalue()
    while data.endswith(bytes(512)):
        data = data[:-512]
    with open(package, "wb") as file:
        file.write(data + bytes(1024))
    return package


def screen(transcript):
    grid = [[(" ", None) for _ in range(WIDTH)] for _ in range(HEIGHT)]
    row = 0
    column = 0
    foreground = None
    text = bytes(transcript).decode("utf-8", "replace")
    index = 0
    while index < len(text):
        character = text[index]
        if character == "\x1b" and index + 1 < len(text) and text[index + 1] == "[":
            end = index + 2
            while end < len(text) and not ("@" <= text[end] <= "~"):
                end += 1
            if end >= len(text):
                break
            raw = text[index + 2:end].lstrip("?")
            values = [int(value) if value.isdigit() else 0 for value in raw.split(";")] if raw else []
            command = text[end]
            if command in ("H", "f"):
                row = max(0, (values[0] if values else 1) - 1)
                column = max(0, (values[1] if len(values) > 1 else 1) - 1)
            elif command == "J" and values and values[0] in (2, 3):
                grid = [[(" ", None) for _ in range(WIDTH)] for _ in range(HEIGHT)]
            elif command == "C":
                column += values[0] if values else 1
            elif command == "G":
                column = max(0, (values[0] if values else 1) - 1)
            elif command == "d":
                row = max(0, (values[0] if values else 1) - 1)
            elif command == "m":
                position = 0
                for value in values or [0]:
                    if value == 0 or value == 39:
                        foreground = None
                    elif 30 <= value <= 37:
                        foreground = ("ansi", value - 30)
                    elif 90 <= value <= 97:
                        foreground = ("ansi", value - 90 + 8)
                    elif value == 38 and position + 2 < len(values) and values[position + 1] == 5:
                        foreground = ("indexed", values[position + 2])
                    elif value == 38 and position + 4 < len(values) and values[position + 1] == 2:
                        foreground = ("rgb", *values[position + 2:position + 5])
                    position += 1
            index = end + 1
            continue
        if character == "\r":
            column = 0
        elif character == "\n":
            row = min(HEIGHT - 1, row + 1)
        elif character >= " ":
            if 0 <= row < HEIGHT and 0 <= column < WIDTH:
                grid[row][column] = (character, foreground)
            column += 1
        index += 1
    return grid


def locate(grid, needle):
    for row, cells in enumerate(grid):
        rendered = "".join(character for character, _ in cells)
        column = rendered.find(needle)
        if column >= 0:
            return row, column
    rendered = [
        "".join(character for character, _ in cells).rstrip()
        for cells in grid
    ]
    raise AssertionError(f"missing {needle!r} in reconstructed screen: {rendered!r}")


with tempfile.TemporaryDirectory(prefix="rustrace-highlighting-pty-") as root:
    package = package_at(root)
    master, slave = pty.openpty()
    fcntl.ioctl(slave, termios.TIOCSWINSZ, struct.pack("HHHH", HEIGHT, WIDTH, 0, 0))

    def child():
        os.setsid()
        fcntl.ioctl(0, termios.TIOCSCTTY, 0)

    environment = {**os.environ, "TERM": "xterm-256color", "COLORTERM": "truecolor"}
    environment.pop("NO_COLOR", None)
    process = subprocess.Popen(
        [BINARY, "work", package],
        stdin=slave,
        stdout=slave,
        stderr=slave,
        preexec_fn=child,
        env=environment,
        cwd=root,
    )
    transcript = bytearray()

    def drain(seconds):
        deadline = time.monotonic() + seconds
        while time.monotonic() < deadline:
            if select.select([master], [], [], 0.025)[0]:
                try:
                    transcript.extend(os.read(master, 65536))
                except OSError:
                    return
            assert len(transcript) <= 2 * 1024 * 1024

    def redraw():
        fcntl.ioctl(slave, termios.TIOCSWINSZ, struct.pack("HHHH", HEIGHT, WIDTH - 1, 0, 0))
        os.kill(process.pid, signal.SIGWINCH)
        drain(0.25)
        fcntl.ioctl(slave, termios.TIOCSWINSZ, struct.pack("HHHH", HEIGHT, WIDTH, 0, 0))
        os.kill(process.pid, signal.SIGWINCH)
        drain(0.5)

    try:
        deadline = time.monotonic() + 20
        while b" files" not in transcript and time.monotonic() < deadline:
            drain(0.1)
        assert b" files" in transcript, repr(bytes(transcript[-5000:]))
        redraw()
        try:
            locate(screen(transcript), "fn main()")
        except AssertionError:
            os.write(master, b"\x1b[17~")
            drain(0.5)
            redraw()
            locate(screen(transcript), "fn main()")

        os.write(master, b"\x1b[F\rif")
        drain(0.75)
        os.write(master, b"\x1b")
        drain(0.25)
        redraw()
        grid = screen(transcript)
        function_row, function_column = locate(grid, "fn main()")
        string_row, string_column = locate(grid, 'let message = "kept";')
        assert grid[function_row][function_column][1] == ("rgb", 203, 166, 247), grid[
            function_row
        ]
        kept_column = string_column + len('let message = "')
        assert grid[string_row][kept_column][1] == ("rgb", 166, 227, 161), grid[
            string_row
        ]

        os.write(master, b"\x11")
        drain(0.25)
        if process.poll() is None:
            os.write(master, b"y")
        deadline = time.monotonic() + 5
        while process.poll() is None and time.monotonic() < deadline:
            drain(0.1)
        assert process.poll() is not None, repr(bytes(transcript[-5000:]))
        assert process.returncode == 0, repr(bytes(transcript[-5000:]))
    finally:
        if process.poll() is None:
            os.killpg(process.pid, signal.SIGKILL)
            process.wait()
        os.close(master)
        os.close(slave)
