"""Owned installed rust-analyzer lifecycle/policy evidence driver."""

import errno
import fcntl
import hashlib
import io
import json
import os
import pathlib
import pty
import select
import signal
import struct
import subprocess
import sys
import tarfile
import termios
import time
import unicodedata

from test_home import isolate
isolate()


binary, mode, evidence_arg = sys.argv[1:]
assert mode in ("valid", "missing_lock", "stale_lock")
binary = str(pathlib.Path(binary).resolve())
evidence = pathlib.Path(evidence_arg).resolve()
evidence.mkdir(parents=True)

source_text = "// naïve 東京 🦀\r\nfn main() { let _ = std::mem::size_of::<u8>(); println!(\"actual LSP\"); }\r\n"
# The installed analyzer returns the stable path candidates used by this probe
# between the two separators, matching the manually verified 24 Right presses.
completion_column = len("fn main() { let _ = std:")
cargo_toml = """[package]
name = "rustrace-actual-lsp-check"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[workspace]
"""
if mode == "stale_lock":
    cargo_toml += '\n[dependencies]\nserde = "1"\n'
lock = """# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "rustrace-actual-lsp-check"
version = "0.1.0"
"""
build_script = """fn main() {
    std::fs::write("BUILD_SCRIPT_RAN", "build scripts were enabled\\n").unwrap();
}
"""
manifest = b'''format_version = 1
course_id = "course"
assignment_id = "installed-lsp-policy"
assignment_version = "v1"
title = "Installed rust-analyzer policy check"
toolchain = "stable"
edition = "2024"
allowed_paths = ["Cargo.toml", "Cargo.lock", "build.rs", "src/*.rs"]
[commands]
check = ["cargo", "check", "--locked", "--offline"]
test = ["cargo", "test", "--locked", "--offline"]
run = ["cargo", "run", "--locked", "--offline"]
clippy = ["cargo", "clippy", "--locked", "--offline"]
format = ["cargo", "fmt"]
'''
files = {
    "Cargo.toml": cargo_toml.encode(),
    "build.rs": build_script.encode(),
    "src/main.rs": source_text.encode(),
}
if mode != "missing_lock":
    files["Cargo.lock"] = lock.encode()

archive = evidence / "assignment.rta"
stream = io.BytesIO()
with tarfile.open(fileobj=stream, mode="w", format=tarfile.USTAR_FORMAT) as package:
    for name, data in [("assignment.toml", manifest)] + [
            ("starter/" + name, contents) for name, contents in files.items()]:
        info = tarfile.TarInfo(name)
        info.size, info.mode = len(data), 0o600
        package.addfile(info, io.BytesIO(data))
data = stream.getvalue()
while data.endswith(bytes(512)):
    data = data[:-512]
archive.write_bytes(data + bytes(1024))
(evidence / "initial.json").write_text(json.dumps({
    "mode": mode,
    "source": source_text,
    "cargo_toml": cargo_toml,
    "lock": lock if mode != "missing_lock" else None,
}, indent=2))
(evidence / "identities.json").write_text(json.dumps({
    "binary": str(pathlib.Path(binary).resolve()),
    "python": sys.executable,
    "sha256": {
        str(path): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in (pathlib.Path(binary), pathlib.Path(__file__), archive)
    },
}, indent=2))

workspace = evidence / "assignment.work"
master, slave = pty.openpty()
fcntl.ioctl(slave, termios.TIOCSWINSZ, struct.pack("HHHH", 32, 140, 0, 0))


def child_setup():
    os.setsid()
    fcntl.ioctl(0, termios.TIOCSCTTY, 0)


wrapper = (
    "import subprocess,termios,sys; before=termios.tcgetattr(0); "
    "result=subprocess.run(sys.argv[1:]); "
    "assert termios.tcgetattr(0)==before, 'terminal mode leaked'; "
    "print('TERMINAL_RESTORED',flush=True); sys.exit(result.returncode)"
)
environment = {
    "HOME": os.environ["HOME"],
    "RUSTUP_HOME": os.environ["RUSTUP_HOME"],
    "CARGO_HOME": os.environ["CARGO_HOME"],
    "XDG_CONFIG_HOME": str(evidence / "xdg-config"),
    "XDG_STATE_HOME": str(evidence / "xdg-state"),
    "PATH": os.environ["PATH"],
    "TERM": "xterm-256color",
    "RUSTUP_AUTO_INSTALL": "0",
    "CARGO_NET_OFFLINE": "true",
    "RUST_ANALYZER": "/forbidden/analyzer",
    "RUSTFLAGS": "--forbidden",
    "RUSTDOCFLAGS": "--forbidden",
    "RA_LOG": "forbidden=trace",
    "RUSTUP_LOG": "forbidden=trace",
    "CARGO_BUILD_RUSTC_WRAPPER": "/forbidden/wrapper",
    "RUSTRACE_SECRET_SENTINEL": "must-not-cross-policy",
}
# Keep this lifecycle/policy driver offline and independent of release discovery.
update_state = evidence / "xdg-state/rustrace/update-state.json"
update_state.parent.mkdir(parents=True)
update_state.write_text(json.dumps({"schema_version": 1, "checks_enabled": False,
                                   "last_attempt": None, "last_success": None,
                                   "next_eligible": None, "latest": None}))
proc = subprocess.Popen(
    [sys.executable, "-c", wrapper, binary, "work", str(archive)],
    stdin=slave,
    stdout=slave,
    stderr=slave,
    cwd=evidence,
    env=environment,
    preexec_fn=child_setup,
)
output = bytearray()
deadline = time.monotonic() + 90


def drain():
    if select.select([master], [], [], .02)[0]:
        try:
            output.extend(os.read(master, 65536))
        except OSError as error:
            if error.errno != errno.EIO:
                raise
    assert len(output) <= 2 * 1024 * 1024, "PTY output exceeded evidence cap"


def wait_for(predicate, label):
    while not predicate():
        assert proc.poll() is None, "work exited before " + label
        assert time.monotonic() < deadline, "deadline waiting for " + label
        drain()


def send(data):
    with (evidence / "input.jsonl").open("a") as log:
        log.write(json.dumps({"bytes_hex": data.hex()}) + "\n")
    os.write(master, data)


def screen_text():
    rows, columns = 32, 140
    screen = [[" "] * columns for _ in range(rows)]
    row = column = 0
    index = 0
    data = bytes(output)
    while index < len(data):
        byte = data[index]
        if byte == 0x1b and index + 1 < len(data) and data[index + 1] == ord("["):
            end = index + 2
            while end < len(data) and not 0x40 <= data[end] <= 0x7e:
                end += 1
            if end == len(data):
                break
            if chr(data[end]) in ("H", "f"):
                parameters = data[index + 2:end].decode("ascii").split(";")
                row = max(0, (int(parameters[0]) if parameters[0] else 1) - 1)
                column = max(0, (int(parameters[1])
                                 if len(parameters) > 1 and parameters[1] else 1) - 1)
            index = end + 1
            continue
        if byte < 0x20 or byte == 0x7f:
            if byte == ord("\r"):
                column = 0
            elif byte == ord("\n"):
                row = min(rows - 1, row + 1)
            elif byte == ord("\b"):
                column = max(0, column - 1)
            index += 1
            continue
        end = index
        while (end < len(data) and data[end] >= 0x20
               and data[end] not in (0x7f, 0x1b)):
            end += 1
        for character in data[index:end].decode("utf-8", errors="ignore"):
            width = (0 if unicodedata.combining(character) else
                     2 if unicodedata.east_asian_width(character) in "WF" else 1)
            if width and 0 <= row < rows and 0 <= column < columns:
                screen[row][column] = character
                if width == 2 and column + 1 < columns:
                    screen[row][column + 1] = " "
            column += width
        index = end
    return "\n".join("".join(line) for line in screen)


editor_buffer_anchors = (
    "[package]",
    'std::fs::write("BUILD_SCRIPT_RAN"',
    'println!("actual LSP")',
)


def active_editor_buffer_anchor():
    screen = screen_text()
    return next((anchor for anchor in editor_buffer_anchors if anchor in screen), None)


def wait_for_shell_ready(label):
    wait_for(lambda: (
        " files" in screen_text()
        and "│output" in screen_text()
        and "Ln 1, Col 1" in screen_text()
        and active_editor_buffer_anchor() is not None
    ), label)


def select_editor_buffer(anchor, label):
    for attempt in range(len(editor_buffer_anchors) + 1):
        current = active_editor_buffer_anchor()
        if current == anchor:
            return
        assert current is not None, label + ": active editor buffer is not visible"
        send(b"\x1b[17~")
        wait_for(
            lambda: active_editor_buffer_anchor() not in (None, current),
            f"{label} buffer advance {attempt + 1}",
        )
    raise AssertionError("unable to select " + label)


def dismiss_transient_toast():
    messages = (
        "switched active buffer",
        "saved",
        "completion requested",
        "language service reload/restart requested",
    )
    if not any(message in screen_text() for message in messages):
        return
    send(b"\x1b")
    wait_for(
        lambda: not any(message in screen_text() for message in messages),
        "transient toast dismissal",
    )


def position_completion_caret(label):
    dismiss_transient_toast()
    send(b"\x1b[H")
    wait_for(lambda: ", Col 1" in screen_text(), label + " line home")
    send(b"\x1b[A")
    wait_for(lambda: "Ln 1, Col 1" in screen_text(), label + " document home")
    send(b"\x1b[B")
    wait_for(lambda: "Ln 2, Col 1" in screen_text(), label + " completion line")
    send(b"\x1b[C" * completion_column)
    expected = f"Ln 2, Col {completion_column + 1}"
    wait_for(lambda: expected in screen_text(), label + " completion caret placement")


def assert_no_persistent_lsp_state(label):
    idle_until = time.monotonic() + .25
    while time.monotonic() < idle_until:
        drain()
    screen = screen_text()
    assert not any(state in screen for state in (
        "LSP reso", "LSP init", "LSP read", "LSP retr", "LSP unav",
        "LSP stop", "LSP off",
    )), label + ": persistent language-service state leaked into the idle shell"


def wait_for_real_server_ready(label):
    # A visible, non-empty completion list proves that this real server answered
    # initialize, received the document, and answered a document request. Process
    # launch and the absence of old UI status text are not readiness authorities.
    position_completion_caret(label)
    attempts = 0
    while " COMPLETE " not in screen_text():
        assert time.monotonic() < deadline, "deadline waiting for " + label
        attempts += 1
        send(b"\x00")
        attempt_deadline = min(deadline, time.monotonic() + 3)
        while time.monotonic() < attempt_deadline:
            drain()
            if " COMPLETE " in screen_text():
                break
        if " COMPLETE " not in screen_text():
            dismiss_transient_toast()
    wait_for(lambda: " COMPLETE " in screen_text(), label + " completion response")
    with (evidence / "readiness.jsonl").open("a") as log:
        log.write(json.dumps({
            "label": label,
            "completion_response_visible": True,
            "attempts": attempts,
        }) + "\n")
    send(b"\x1b")
    wait_for(lambda: " COMPLETE " not in screen_text(), label + " completion dismissal")
    send(b"\x1b[H")
    wait_for(lambda: "Ln 2, Col 1" in screen_text(), label + " completion line reset")
    send(b"\x1b[A")
    wait_for(lambda: "Ln 1, Col 1" in screen_text(), label + " document reset")


def process_rows():
    text = subprocess.check_output(
        ["ps", "-axo", "pid=,ppid=,pgid=,command="], text=True,
        env={"PATH": environment["PATH"]},
    )
    rows = []
    for line in text.splitlines():
        fields = line.strip().split(None, 3)
        if len(fields) == 4:
            rows.append({"pid": int(fields[0]), "ppid": int(fields[1]),
                         "pgid": int(fields[2]), "command": fields[3]})
    return rows


def owned_processes():
    rows = process_rows()
    owned = {proc.pid}
    changed = True
    while changed:
        changed = False
        for row in rows:
            if row["ppid"] in owned and row["pid"] not in owned:
                owned.add(row["pid"])
                changed = True
    return [row for row in rows if row["pid"] in owned]


def analyzer_pids():
    return [row["pid"] for row in owned_processes()
            if "rust-analyzer" in row["command"]]


def resolution_files():
    return sorted((workspace / ".rustrace").glob("language-server-resolution-*.json"))


def snapshot_processes(name):
    (evidence / name).write_text(json.dumps(owned_processes(), indent=2))


def target_inventory():
    target = workspace / "target"
    if not target.exists():
        return []
    return [str(path.relative_to(workspace)) for path in sorted(target.rglob("*"))]


try:
    wait_for(lambda: b" files" in output, "production editor")
    wait_for_shell_ready("production editor shell")
    wait_for(lambda: resolution_files() and analyzer_pids(), "installed analyzer launch")
    select_editor_buffer('std::fs::write("BUILD_SCRIPT_RAN"', "build script buffer")
    select_editor_buffer('println!("actual LSP")', "source buffer")
    wait_for_real_server_ready("installed analyzer initialize")
    assert_no_persistent_lsp_state("installed analyzer initialize")
    initial_pid = analyzer_pids()[0]
    observed_analyzer_pids = {initial_pid}
    snapshot_processes("processes-initial.json")

    if mode == "valid":
        send(b"\x1b[B\x1b[F\x1b[D?")
        wait_for(
            lambda: '?}' in screen_text() and "│output · Syntax Error:" in screen_text(),
            "real native diagnostic",
        )
        diagnostic_screen = screen_text()
        diagnostic_row = next(line for line in diagnostic_screen.splitlines()
                              if 'println!("actual LSP")' in line)
        assert "│fn main()" in diagnostic_row, \
            "real native diagnostic shifted the source column"
        (evidence / "native-diagnostic-screen.txt").write_text(diagnostic_screen)
        send(b"\x7f")
        wait_for(
            lambda: '?}' not in screen_text()
            and "│output · Syntax Error:" not in screen_text(),
            "real native diagnostic clear",
        )
        (evidence / "native-diagnostic-cleared-screen.txt").write_text(screen_text())
        send(b"\x1b[H\x1b[A")
        wait_for(lambda: "Ln 1, Col 1" in screen_text(), "post-diagnostic document reset")
        send(b"X")
        wait_for(
            lambda: "X// naïve" in screen_text() and "Ln 1, Col 2" in screen_text(),
            "first modified state",
        )
        expected = "X" + source_text
        wait_for(lambda: (workspace / "src/main.rs").read_bytes() == expected.encode(),
                 "first autosaved actual-server edit")
        os.kill(initial_pid, signal.SIGKILL)
        wait_for(lambda: initial_pid not in analyzer_pids(), "owned analyzer crash")
        send(b"Y")
        wait_for(
            lambda: "XY// naïve" in screen_text() and "Ln 1, Col 3" in screen_text(),
            "restart modified state",
        )
        expected = "XY" + source_text
        wait_for(lambda: (workspace / "src/main.rs").read_bytes() == expected.encode(),
                 "autosave while analyzer restarts")
        wait_for(lambda: len(resolution_files()) >= 2
                 and any(pid != initial_pid for pid in analyzer_pids()),
                 "fresh installed analyzer restart")
        wait_for_real_server_ready("restarted analyzer initialize")
        assert_no_persistent_lsp_state("restarted analyzer initialize")
        observed_analyzer_pids.update(analyzer_pids())
        snapshot_processes("processes-restarted.json")
        pre_reload_pids = set(analyzer_pids())
        pre_reload_resolutions = len(resolution_files())
        send(b"\x1b[19~")
        wait_for(lambda: "language service reload/restart requested" in screen_text(),
                 "explicit installed analyzer reload")
        wait_for_real_server_ready("reloaded analyzer initialize")
        assert_no_persistent_lsp_state("reloaded analyzer initialize")
        assert set(analyzer_pids()) == pre_reload_pids, \
            "supported workspace reload replaced the installed analyzer process"
        assert len(resolution_files()) == pre_reload_resolutions, \
            "supported workspace reload redundantly resolved the installed analyzer"
        observed_analyzer_pids.update(analyzer_pids())
        snapshot_processes("processes-reloaded.json")
    else:
        expected = source_text
        until = time.monotonic() + 3
        while time.monotonic() < until:
            drain()

    assert not (workspace / "BUILD_SCRIPT_RAN").exists()
    if mode == "missing_lock":
        assert not (workspace / "Cargo.lock").exists(), "missing lock was created"
    else:
        assert (workspace / "Cargo.lock").read_text() == lock, "lockfile changed"
    (evidence / "target-inventory.json").write_text(json.dumps(target_inventory(), indent=2))
    (evidence / "result.json").write_text(json.dumps({
        "mode": mode,
        "expected_source_sha256": hashlib.sha256(expected.encode()).hexdigest(),
        "resolution_artifacts": [path.name for path in resolution_files()],
        "initial_analyzer_pid": initial_pid,
        "target_entries": len(target_inventory()),
        "build_script_ran": False,
        "lock_present": (workspace / "Cargo.lock").exists(),
        "native_diagnostic_observed": mode == "valid",
    }, indent=2))
    send(b"\x11")
    while proc.poll() is None:
        assert time.monotonic() < deadline, "work did not quit"
        drain()
    while select.select([master], [], [], .05)[0]:
        before = len(output)
        drain()
        if len(output) == before:
            break
    assert proc.returncode == 0, "work or terminal restoration failed"
    assert b"TERMINAL_RESTORED" in output
    assert b"\x1b[?1049l" in output and b"\x1b[?2004l" in output
    live_pids = {row["pid"] for row in process_rows()}
    assert observed_analyzer_pids.isdisjoint(live_pids), \
        "an observed analyzer remained live after quit"
    snapshot_processes("processes-after.json")
finally:
    (evidence / "pty.bin").write_bytes(output)
    if proc.poll() is None:
        os.killpg(proc.pid, signal.SIGKILL)
        proc.wait()
    os.close(master)
    os.close(slave)
